// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNkvjh2tr9JtP_czQL-0Yj5_Ex0CJHWk4',
    appId: '1:232084878775:web:55137217d456f4a6896432',
    messagingSenderId: '232084878775',
    projectId: 'myproject-5fa66',
    authDomain: 'myproject-5fa66.firebaseapp.com',
    storageBucket: 'myproject-5fa66.appspot.com',
    measurementId: 'G-K6SV8YB499',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6W6ziFkz9NjqiQzWbF_T4s8WfVLuser8',
    appId: '1:232084878775:android:41438e5c1960788f896432',
    messagingSenderId: '232084878775',
    projectId: 'myproject-5fa66',
    storageBucket: 'myproject-5fa66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARX5fIpwafQiv1H8JeK8klTCOsGsta1MY',
    appId: '1:232084878775:ios:2da78202c229669a896432',
    messagingSenderId: '232084878775',
    projectId: 'myproject-5fa66',
    storageBucket: 'myproject-5fa66.appspot.com',
    iosClientId: '232084878775-5f09tk2qm7ibqrn36e2cvi6514visg8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARX5fIpwafQiv1H8JeK8klTCOsGsta1MY',
    appId: '1:232084878775:ios:2da78202c229669a896432',
    messagingSenderId: '232084878775',
    projectId: 'myproject-5fa66',
    storageBucket: 'myproject-5fa66.appspot.com',
    iosClientId: '232084878775-5f09tk2qm7ibqrn36e2cvi6514visg8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mCommerce',
  );
}
